const mongoose = require('mongoose');
const dotenv = require('dotenv');
const path = require('path');
const PickupRequest = require('./models/PickupRequest');

dotenv.config({ path: path.join(__dirname, '../.env') });

const seedData = [
  {
    requestId: 'ET-2026-1001',
    name: 'Aarav Patil',
    phone: '9823012345',
    email: 'aarav.patil@example.com',
    wasteCategory: 'Plastic',
    quantity: '15 kg',
    address: 'Plot 42, Green Avenue, Main Road',
    city: 'Sangli',
    locality: 'Vishrambag',
    pickupDate: '2026-09-28',
    pickupTime: '10:00 AM - 12:00 PM',
    notes: 'Plastic bottles and packaging materials cleaned.',
    status: 'Pending',
  },
  {
    requestId: 'ET-2026-1002',
    name: 'Priya Kulkarni',
    phone: '9765432109',
    email: 'priya.k@example.com',
    wasteCategory: 'Paper',
    quantity: '25 kg',
    address: 'Flat 301, Sunshine Heights, Near Bus Stand',
    city: 'Ashta',
    locality: 'Market Yard',
    pickupDate: '2026-09-28',
    pickupTime: '02:00 PM - 04:00 PM',
    notes: 'Old newspapers and corrugated boxes bundled.',
    status: 'Scheduled',
  },
  {
    requestId: 'ET-2026-1003',
    name: 'Vikram Shinde',
    phone: '9422056789',
    email: 'vikram.shinde@example.com',
    wasteCategory: 'E-Waste',
    quantity: '10 kg',
    address: 'House No 105, Station Road',
    city: 'Islampur',
    locality: 'Uran Islampur',
    pickupDate: '2026-09-29',
    pickupTime: '09:00 AM - 11:00 AM',
    notes: 'Old monitor, keyboards, and broken printer.',
    status: 'Assigned',
  },
  {
    requestId: 'ET-2026-1004',
    name: 'Ananya Deshmukh',
    phone: '9890123456',
    email: 'ananya.d@example.com',
    wasteCategory: 'Organic',
    quantity: '8 kg',
    address: 'Bungalow 12, Tarabai Park',
    city: 'Kolhapur',
    locality: 'Tarabai Park',
    pickupDate: '2026-09-27',
    pickupTime: '08:00 AM - 10:00 AM',
    notes: 'Garden waste and organic kitchen scraps.',
    status: 'Picked Up',
  },
  {
    requestId: 'ET-2026-1005',
    name: 'Rohan Joshi',
    phone: '9158098765',
    email: 'rohan.j@example.com',
    wasteCategory: 'Glass',
    quantity: '12 kg',
    address: 'Phase 2, IT Park, Hinjewadi',
    city: 'Pune',
    locality: 'Hinjewadi',
    pickupDate: '2026-09-26',
    pickupTime: '11:00 AM - 01:00 PM',
    notes: 'Glass bottles carefully packed in cardboard box.',
    status: 'Completed',
  },
  {
    requestId: 'ET-2026-1006',
    name: 'Sneha Chavan',
    phone: '9822114433',
    email: 'sneha.c@example.com',
    wasteCategory: 'Metal',
    quantity: '18 kg',
    address: 'Shop 4, Industrial Area',
    city: 'Sangli',
    locality: 'Kupwad MIDC',
    pickupDate: '2026-09-29',
    pickupTime: '03:00 PM - 05:00 PM',
    notes: 'Aluminium scrap and steel containers.',
    status: 'Pending',
  },
  {
    requestId: 'ET-2026-1007',
    name: 'Aditya Pawar',
    phone: '9970112233',
    email: 'aditya.pawar@example.com',
    wasteCategory: 'General Waste',
    quantity: '20 kg',
    address: 'Near Old Rajwada, Main Square',
    city: 'Ashta',
    locality: 'Peth Bhag',
    pickupDate: '2026-09-28',
    pickupTime: '10:00 AM - 12:00 PM',
    notes: 'Non-recyclable packaging and dry household waste.',
    status: 'Scheduled',
  },
  {
    requestId: 'ET-2026-1008',
    name: 'Meera Kulkarni',
    phone: '9860445566',
    email: 'meera.k@example.com',
    wasteCategory: 'Plastic',
    quantity: '30 kg',
    address: 'Flat 504, Eco Valley, Kothrud',
    city: 'Pune',
    locality: 'Kothrud',
    pickupDate: '2026-09-25',
    pickupTime: '01:00 PM - 03:00 PM',
    notes: 'High density polyethylene containers and crates.',
    status: 'Completed',
  },
  {
    requestId: 'ET-2026-1009',
    name: 'Siddharth Mane',
    phone: '9423887766',
    email: 'sid.mane@example.com',
    wasteCategory: 'Paper',
    quantity: '40 kg',
    address: 'College Road, Near Shivaji University',
    city: 'Kolhapur',
    locality: 'Vidyanagar',
    pickupDate: '2026-09-26',
    pickupTime: '04:00 PM - 06:00 PM',
    notes: 'Office documents shredded and boxed.',
    status: 'Completed',
  },
  {
    requestId: 'ET-2026-1010',
    name: 'Pooja Jadhav',
    phone: '9890554433',
    email: 'pooja.j@example.com',
    wasteCategory: 'E-Waste',
    quantity: '5 kg',
    address: 'Plot 8, Bahe Road',
    city: 'Islampur',
    locality: 'Warna Nagar',
    pickupDate: '2026-09-30',
    pickupTime: '10:00 AM - 12:00 PM',
    notes: 'Old cellphones, chargers and battery packs.',
    status: 'Pending',
  },
  {
    requestId: 'ET-2026-1011',
    name: 'Ganesh More',
    phone: '9762334411',
    email: 'ganesh.more@example.com',
    wasteCategory: 'Organic',
    quantity: '14 kg',
    address: 'Gaon Bhag, Near Maruti Temple',
    city: 'Sangli',
    locality: 'Gaon Bhag',
    pickupDate: '2026-09-27',
    pickupTime: '07:00 AM - 09:00 AM',
    notes: 'Compostable vegetable market waste.',
    status: 'Picked Up',
  },
  {
    requestId: 'ET-2026-1012',
    name: 'Kavita Thorat',
    phone: '9850998877',
    email: 'kavita.t@example.com',
    wasteCategory: 'Glass',
    quantity: '7 kg',
    address: 'Viman Nagar, Near Phoenix Mall',
    city: 'Pune',
    locality: 'Viman Nagar',
    pickupDate: '2026-09-24',
    pickupTime: '02:00 PM - 04:00 PM',
    notes: 'Wine bottles and window glass panes.',
    status: 'Completed',
  },
  {
    requestId: 'ET-2026-1013',
    name: 'Sachin Bhosale',
    phone: '9421223344',
    email: 'sachin.b@example.com',
    wasteCategory: 'Metal',
    quantity: '35 kg',
    address: 'Shiroli MIDC, Block C',
    city: 'Kolhapur',
    locality: 'Shiroli',
    pickupDate: '2026-09-29',
    pickupTime: '11:00 AM - 01:00 PM',
    notes: 'Iron sheets and brass hardware scrap.',
    status: 'Assigned',
  },
  {
    requestId: 'ET-2026-1014',
    name: 'Tanvi Salunkhe',
    phone: '9823556677',
    email: 'tanvi.s@example.com',
    wasteCategory: 'Plastic',
    quantity: '12 kg',
    address: 'Subhash Nagar, Road No 3',
    city: 'Ashta',
    locality: 'Subhash Nagar',
    pickupDate: '2026-09-27',
    pickupTime: '03:00 PM - 05:00 PM',
    notes: 'Plastic buckets and milk pouches cleaned.',
    status: 'Cancelled',
  },
  {
    requestId: 'ET-2026-1015',
    name: 'Nikhil Mohite',
    phone: '9158667788',
    email: 'nikhil.m@example.com',
    wasteCategory: 'General Waste',
    quantity: '16 kg',
    address: 'Baner Road, High Street',
    city: 'Pune',
    locality: 'Baner',
    pickupDate: '2026-09-28',
    pickupTime: '09:00 AM - 11:00 AM',
    notes: 'Mixed dry waste from store cleanup.',
    status: 'Scheduled',
  },
];

const seedDB = async () => {
  try {
    const mongoURI = process.env.MONGODB_URI || 'mongodb://127.0.0.1:27017/ecotrack';
    await mongoose.connect(mongoURI);
    console.log('Connected to MongoDB for seeding...');

    await PickupRequest.deleteMany({});
    console.log('Cleared existing pickup requests.');

    await PickupRequest.insertMany(seedData);
    console.log(`Successfully seeded ${seedData.length} pickup requests into database!`);

    process.exit(0);
  } catch (error) {
    console.error('Error seeding database:', error);
    process.exit(1);
  }
};

seedDB();
