const mongoose = require('mongoose');
const dotenv = require('dotenv');
const path = require('path');
const PickupRequest = require('./models/PickupRequest');

dotenv.config({ path: path.join(__dirname, '../.env') });

const seedData = [
  // WAVE 1: Ashta East / Market Yard Cluster
  {
    requestId: 'ET-2026-1001',
    name: 'Aarav Patil',
    phone: '9823012345',
    email: 'aarav.patil@example.com',
    wasteCategory: 'Plastic',
    quantity: '15 kg',
    address: 'Plot 42, Green Avenue, Main Road',
    city: 'Ashta',
    locality: 'Ashta East',
    pickupDate: '2026-09-28',
    pickupTime: '10:00 AM - 12:00 PM',
    notes: 'Plastic containers rinsed and tied in bundles.',
    status: 'Pending',
    ecoScore: 85,
    ecoPoints: 50,
    estimatedDiversionKg: 12.8,
    collectionWaveId: 'WAVE-ASHT-ASHTAEAST',
    collectionPriority: 'MEDIUM',
  },
  {
    requestId: 'ET-2026-1002',
    name: 'Priya Kulkarni',
    phone: '9765432109',
    email: 'priya.k@example.com',
    wasteCategory: 'Paper',
    quantity: '25 kg',
    address: 'Flat 301, Sunshine Heights, Near Bus Stand',
    city: 'Ashta',
    locality: 'Ashta East',
    pickupDate: '2026-09-28',
    pickupTime: '10:00 AM - 12:00 PM',
    notes: 'Old newspapers and corrugated boxes bundled.',
    status: 'Scheduled',
    ecoScore: 90,
    ecoPoints: 45,
    estimatedDiversionKg: 22.5,
    collectionWaveId: 'WAVE-ASHT-ASHTAEAST',
    collectionPriority: 'MEDIUM',
  },
  {
    requestId: 'ET-2026-1007',
    name: 'Aditya Pawar',
    phone: '9970112233',
    email: 'aditya.pawar@example.com',
    wasteCategory: 'Metal',
    quantity: '8 kg',
    address: 'Near Old Rajwada, Main Square',
    city: 'Ashta',
    locality: 'Ashta East',
    pickupDate: '2026-09-28',
    pickupTime: '10:00 AM - 12:00 PM',
    notes: 'Cleaned aluminium beverage cans.',
    status: 'Scheduled',
    ecoScore: 95,
    ecoPoints: 55,
    estimatedDiversionKg: 7.6,
    collectionWaveId: 'WAVE-ASHT-ASHTAEAST',
    collectionPriority: 'MEDIUM',
  },

  // WAVE 2: Sangli Road / Vishrambag Cluster
  {
    requestId: 'ET-2026-1003',
    name: 'Vikram Shinde',
    phone: '9422056789',
    email: 'vikram.shinde@example.com',
    wasteCategory: 'E-Waste',
    quantity: '18 kg',
    address: 'House No 105, Station Road',
    city: 'Sangli',
    locality: 'Sangli Road',
    pickupDate: '2026-09-29',
    pickupTime: '09:00 AM - 11:00 AM',
    notes: 'Old monitor, keyboards, and broken printer.',
    status: 'Assigned',
    ecoScore: 82,
    ecoPoints: 70,
    estimatedDiversionKg: 13.5,
    collectionWaveId: 'WAVE-SANG-SANGLIROAD',
    collectionPriority: 'HIGH',
  },
  {
    requestId: 'ET-2026-1006',
    name: 'Sneha Chavan',
    phone: '9822114433',
    email: 'sneha.c@example.com',
    wasteCategory: 'Plastic',
    quantity: '12 kg',
    address: 'Shop 4, Industrial Area',
    city: 'Sangli',
    locality: 'Sangli Road',
    pickupDate: '2026-09-29',
    pickupTime: '09:00 AM - 11:00 AM',
    notes: 'Aluminium scrap and steel containers.',
    status: 'Pending',
    ecoScore: 88,
    ecoPoints: 50,
    estimatedDiversionKg: 10.2,
    collectionWaveId: 'WAVE-SANG-SANGLIROAD',
    collectionPriority: 'HIGH',
  },
  {
    requestId: 'ET-2026-1011',
    name: 'Ganesh More',
    phone: '9762334411',
    email: 'ganesh.more@example.com',
    wasteCategory: 'Organic',
    quantity: '14 kg',
    address: 'Gaon Bhag, Near Maruti Temple',
    city: 'Sangli',
    locality: 'Sangli Road',
    pickupDate: '2026-09-29',
    pickupTime: '09:00 AM - 11:00 AM',
    notes: 'Compostable vegetable market waste.',
    status: 'Picked Up',
    ecoScore: 78,
    ecoPoints: 40,
    estimatedDiversionKg: 12.6,
    collectionWaveId: 'WAVE-SANG-SANGLIROAD',
    collectionPriority: 'HIGH',
  },

  // WAVE 3: Islampur Warna Nagar Cluster
  {
    requestId: 'ET-2026-1010',
    name: 'Pooja Jadhav',
    phone: '9890554433',
    email: 'pooja.j@example.com',
    wasteCategory: 'E-Waste',
    quantity: '6 kg',
    address: 'Plot 8, Bahe Road',
    city: 'Islampur',
    locality: 'Warna Nagar',
    pickupDate: '2026-09-30',
    pickupTime: '10:00 AM - 12:00 PM',
    notes: 'Old cellphones, chargers and battery packs.',
    status: 'Pending',
    ecoScore: 80,
    ecoPoints: 70,
    estimatedDiversionKg: 4.5,
    collectionWaveId: 'WAVE-ISLA-WARNANAGAR',
    collectionPriority: 'HIGH',
  },
  {
    requestId: 'ET-2026-1014',
    name: 'Tanvi Salunkhe',
    phone: '9823556677',
    email: 'tanvi.s@example.com',
    wasteCategory: 'Plastic',
    quantity: '10 kg',
    address: 'Subhash Nagar, Road No 3',
    city: 'Islampur',
    locality: 'Warna Nagar',
    pickupDate: '2026-09-30',
    pickupTime: '10:00 AM - 12:00 PM',
    notes: 'Plastic buckets and milk pouches cleaned.',
    status: 'Scheduled',
    ecoScore: 85,
    ecoPoints: 50,
    estimatedDiversionKg: 8.5,
    collectionWaveId: 'WAVE-ISLA-WARNANAGAR',
    collectionPriority: 'HIGH',
  },

  // WAVE 4: Kolhapur Tarabai Park Cluster
  {
    requestId: 'ET-2026-1004',
    name: 'Ananya Deshmukh',
    phone: '9890123456',
    email: 'ananya.d@example.com',
    wasteCategory: 'Organic',
    quantity: '8 kg',
    address: 'Bungalow 12, Tarabai Park',
    city: 'Kolhapur',
    locality: 'Tarabai Park',
    pickupDate: '2026-09-27',
    pickupTime: '08:00 AM - 10:00 AM',
    notes: 'Garden waste and organic kitchen scraps.',
    status: 'Picked Up',
    ecoScore: 75,
    ecoPoints: 40,
    estimatedDiversionKg: 7.2,
    collectionWaveId: 'WAVE-KOLH-TARABAIPARK',
    collectionPriority: 'MEDIUM',
  },
  {
    requestId: 'ET-2026-1009',
    name: 'Siddharth Mane',
    phone: '9423887766',
    email: 'sid.mane@example.com',
    wasteCategory: 'Paper',
    quantity: '40 kg',
    address: 'College Road, Near Shivaji University',
    city: 'Kolhapur',
    locality: 'Tarabai Park',
    pickupDate: '2026-09-27',
    pickupTime: '08:00 AM - 10:00 AM',
    notes: 'Office documents shredded and boxed.',
    status: 'Completed',
    ecoScore: 92,
    ecoPoints: 45,
    estimatedDiversionKg: 36.0,
    collectionWaveId: 'WAVE-KOLH-TARABAIPARK',
    collectionPriority: 'MEDIUM',
  },
  {
    requestId: 'ET-2026-1013',
    name: 'Sachin Bhosale',
    phone: '9421223344',
    email: 'sachin.b@example.com',
    wasteCategory: 'Metal',
    quantity: '35 kg',
    address: 'Shiroli MIDC, Block C',
    city: 'Kolhapur',
    locality: 'Tarabai Park',
    pickupDate: '2026-09-27',
    pickupTime: '08:00 AM - 10:00 AM',
    notes: 'Iron sheets and brass hardware scrap.',
    status: 'Assigned',
    ecoScore: 95,
    ecoPoints: 55,
    estimatedDiversionKg: 33.25,
    collectionWaveId: 'WAVE-KOLH-TARABAIPARK',
    collectionPriority: 'HIGH',
  },

  // WAVE 5: Pune Hinjewadi & Kothrud Cluster
  {
    requestId: 'ET-2026-1005',
    name: 'Rohan Joshi',
    phone: '9158098765',
    email: 'rohan.j@example.com',
    wasteCategory: 'Glass',
    quantity: '12 kg',
    address: 'Phase 2, IT Park, Hinjewadi',
    city: 'Pune',
    locality: 'Hinjewadi',
    pickupDate: '2026-09-26',
    pickupTime: '11:00 AM - 01:00 PM',
    notes: 'Glass bottles carefully packed in cardboard box.',
    status: 'Completed',
    ecoScore: 88,
    ecoPoints: 45,
    estimatedDiversionKg: 10.2,
    collectionWaveId: 'WAVE-PUNE-HINJEWADI',
    collectionPriority: 'MEDIUM',
  },
  {
    requestId: 'ET-2026-1008',
    name: 'Meera Kulkarni',
    phone: '9860445566',
    email: 'meera.k@example.com',
    wasteCategory: 'Plastic',
    quantity: '30 kg',
    address: 'Flat 504, Eco Valley, Kothrud',
    city: 'Pune',
    locality: 'Hinjewadi',
    pickupDate: '2026-09-26',
    pickupTime: '11:00 AM - 01:00 PM',
    notes: 'High density polyethylene containers and crates.',
    status: 'Completed',
    ecoScore: 90,
    ecoPoints: 50,
    estimatedDiversionKg: 25.5,
    collectionWaveId: 'WAVE-PUNE-HINJEWADI',
    collectionPriority: 'HIGH',
  },
  {
    requestId: 'ET-2026-1012',
    name: 'Kavita Thorat',
    phone: '9850998877',
    email: 'kavita.t@example.com',
    wasteCategory: 'Glass',
    quantity: '7 kg',
    address: 'Viman Nagar, Near Phoenix Mall',
    city: 'Pune',
    locality: 'Hinjewadi',
    pickupDate: '2026-09-26',
    pickupTime: '11:00 AM - 01:00 PM',
    notes: 'Wine bottles and window glass panes.',
    status: 'Completed',
    ecoScore: 85,
    ecoPoints: 45,
    estimatedDiversionKg: 5.95,
    collectionWaveId: 'WAVE-PUNE-HINJEWADI',
    collectionPriority: 'MEDIUM',
  },
  {
    requestId: 'ET-2026-1015',
    name: 'Nikhil Mohite',
    phone: '9158667788',
    email: 'nikhil.m@example.com',
    wasteCategory: 'General Waste',
    quantity: '16 kg',
    address: 'Baner Road, High Street',
    city: 'Pune',
    locality: 'Hinjewadi',
    pickupDate: '2026-09-28',
    pickupTime: '09:00 AM - 11:00 AM',
    notes: 'Mixed dry waste from store cleanup.',
    status: 'Scheduled',
    ecoScore: 50,
    ecoPoints: 20,
    estimatedDiversionKg: 2.4,
    collectionWaveId: 'WAVE-PUNE-HINJEWADI',
    collectionPriority: 'LOW',
  },
];

const seedDB = async () => {
  try {
    const mongoURI = process.env.MONGODB_URI || 'mongodb://127.0.0.1:27017/ecotrack';
    await mongoose.connect(mongoURI);
    console.log('Connected to MongoDB for seeding...');

    await PickupRequest.deleteMany({});
    console.log('Cleared existing pickup requests.');

    await PickupRequest.insertMany(seedData);
    console.log(`Successfully seeded ${seedData.length} EcoFlow pickup requests into database!`);

    process.exit(0);
  } catch (error) {
    console.error('Error seeding database:', error);
    process.exit(1);
  }
};

seedDB();
